version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_URI_TEST=${MONGODB_URI_TEST}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    entrypoint: ["sh", "entrypoint.sh"]

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: